FROM python:rc-buster

RUN git clone https://github.com/grycap/scar.git

WORKDIR /scar

RUN pip3 install pyinstaller
RUN pip3 install -r requirements.txt

CMD pyinstaller --noconfirm /scar/scar/scarcli.py
