name: lambda runtime build

on:
 push:
  branches:
   - 2020-09-06-lambda-optimise

 pull_request:
  branches:
   - 2020-09-06-lambda-optimise

jobs:

 build:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v1
   - name: build
     run: ./build-runtime.sh

   - name: Upload binaries
     uses: svenstaro/upload-release-action@v2
     with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: ./runtime/runtime.zip
       asset_name: runtime.zip
       tag: ${{ github.ref }}
       overwrite: true
       body: "The custom runtime for lambda"
