name: build dockers

on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master

jobs:

 cd:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v1
   - name: Docker login
     run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
   - name: Build
     run: docker build -f Dockerfile.scarkeybase -t thedavidmeister/scarkeybase .
   - name: Push
     run: docker push thedavidmeister/scarkeybase
